/* CREATE DATABASE STRUCTURE */
CREATE TABLE IF NOT EXISTS CH_CLASSES(ID INT PRIMARY KEY, LABEL VARCHAR(100));

CREATE TABLE IF NOT EXISTS CH_STUDENT(EMAIL VARCHAR(100) PRIMARY KEY, PASSWD VARCHAR(200), LASTNAME_FIRSTNAME VARCHAR(100), MOTIVATION VARCHAR(4000), CLASSES_REGISTERED VARCHAR(50) );

CREATE TABLE IF NOT EXISTS CH_ADMIN(EMAIL VARCHAR(50) PRIMARY KEY);

/* INIT DATABASE CONTENT */
TRUNCATE TABLE CH_ADMIN;
INSERT INTO CH_ADMIN(EMAIL) VALUES('drighetto@gmail.com');
TRUNCATE TABLE CH_CLASSES;
INSERT INTO CH_CLASSES(ID,LABEL) VALUES(1,'Principles of security of web applications - introduction');
INSERT INTO CH_CLASSES(ID,LABEL) VALUES(2,'From the software architecture to implementation');
INSERT INTO CH_CLASSES(ID,LABEL) VALUES(3,'Apply security check on applications, Hacking technics');
INSERT INTO CH_CLASSES(ID,LABEL) VALUES(4,'Secure infrastructure to host applications');
INSERT INTO CH_CLASSES(ID,LABEL) VALUES(5,'Secure coding explanantion, Java Security');
INSERT INTO CH_CLASSES(ID,LABEL) VALUES(6,'Security databases, the example of Oracle');
INSERT INTO CH_CLASSES(ID,LABEL) VALUES(7,'Approach of a Software Developement Life Cycle');
INSERT INTO CH_CLASSES(ID,LABEL) VALUES(8,'Malware and their analysis');
INSERT INTO CH_CLASSES(ID,LABEL) VALUES(9,'Using the Cloud');
INSERT INTO CH_CLASSES(ID,LABEL) VALUES(10,'Online payment');
TRUNCATE TABLE CH_STUDENT;
--Raw Password: "AZERTY12345"
INSERT INTO CH_STUDENT(EMAIL,PASSWD,LASTNAME_FIRSTNAME,MOTIVATION, CLASSES_REGISTERED) VALUES('drighetto@gmail.com','54BEC2BE01D0DEF1340429C0703BD1F7DABDA986','Dominique Righetto', 'Envie d''apprendre', '1,3,5');
INSERT INTO CH_STUDENT(EMAIL,PASSWD,LASTNAME_FIRSTNAME,MOTIVATION) VALUES('arighetto@gmail.com','54BEC2BE01D0DEF1340429C0703BD1F7DABDA986','Amélie Righetto', 'Envie de découvrir la sécurité applicative');
INSERT INTO CH_STUDENT(EMAIL,PASSWD,LASTNAME_FIRSTNAME,MOTIVATION) VALUES('bgirondon@gmail.com','54BEC2BE01D0DEF1340429C0703BD1F7DABDA986','Benoit Girondon', 'Envie de découvrir la sécu');
COMMIT;

